### ISSUE TITLE
jq => parse error: Invalid numeric literal

### ISSUE THREAD

**Issue by turkenh** [TranceMaster86/docker-reg-gc#2]
I am trying to run the script on RHEL 7 but got the error on title, see execution output below:

```
$ ./docker-reg-gc.sh
+ LIVINGDAYS=150
+ DOCKER_REGISTRY=http://localhost:5000/v2
+ ACCEPT_HEADER='Accept: application/vnd.docker.distribution.manifest.v2+json'
++ get_repositories
++ curl -Ls GET http://localhost:5000/v2/_catalog
++ jq -r '."repositories"[]'
parse error: Invalid numeric literal at line 1, column 18
(23) Failed writing body
+ REPORITORIES=
```

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
...
$ jq --version # installed with yum
jq-1.5
$ curl --version
curl 7.29.0
$ awk --version
GNU Awk 4.0.2
```

**Comment by turkenh** [comment]
I could run the script by deleting 'GET's (as GET is default) in all curl requests:

```
- curl -Ls GET "${DOCKER_REGISTRY}"/_catalog
+ curl -Ls "${DOCKER_REGISTRY}"/_catalog
```

As far as I know curl requires "-X" before request type, am I missing something or is this kind of a curl version mismatch?

**Comment by TranceMaster86** [comment]
It can be a version mismatch. I'll have a look for it.

**Comment by TranceMaster86** [comment]
Thats really interesting, we are using the same Versions.

curl 7.29.0
jq-1.5
Awk 4.0.2

the script runs for me.
I could reproduce the error when I set the wrong registry url. Can you try to set that in double quotes?
`DOCKER_REGISTRY="http://localhost:5000/v2"`

Also let me know if you get an answer by calling `curl -Ls GET http://localhost:5000/v2/_catalog` directly

**Comment by turkenh** [comment]
Wow, 11 months after😀
I could hardly remember why I needed these scripts.
But thanks for keeping your promise ;)

**Comment by TranceMaster86** [comment]
Sorry ;)

**Comment by TranceMaster86** [comment]
What do you think can we close it?

**Comment by turkenh** [comment]
Yes, we can close as it looks like specific to my environment and a workaroud already available.
